### ISSUE TITLE
Duplicate interaction check needs to occur when the interaction is set up, not on replay

### ISSUE THREAD

**Issue by bethesque** [bethesque/pact-mock_service#1]
Otherwise the error does not bubble up to the client (eg the javascript client) in a helpful way, as the response may not be logged.

```
I, [2014-12-17T16:16:36.687916 #52188]  INFO -- : Received request POST /thing?lastName=Smith&firstName=Mary
D, [2014-12-17T16:16:36.688114 #52188] DEBUG -- : {
  "path": "/thing",
  "query": "lastName=Smith&firstName=Mary",
  "method": "post",
  "headers": {
    "Content-Type": "application/x-www-form-urlencoded",
    "Origin": "http://localhost:9876",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34",
    "Referer": "http://localhost:9876/context.html",
    "Accept": "*/*",
    "Connection": "Keep-Alive",
    "Accept-Encoding": "gzip",
    "Accept-Language": "en-AU,*",
    "Host": "localhost:1234",
    "Version": "HTTP/1.1"
  }
}
E, [2014-12-17T16:16:36.688534 #52188] ERROR -- : Error ocurred in mock service:
E, [2014-12-17T16:16:36.688849 #52188] ERROR -- : #<RuntimeError: Interaction with same description (another request for hello) and provider state () already exists>
D, [2014-12-17T16:16:36.689348 #52188] DEBUG -- : [
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/interactions_filter.rb:39:in `<<'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/mock_service/interaction_replay.rb:36:in `add_verified_interaction'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/mock_service/interaction_replay.rb:63:in `handle_matched_interaction'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/mock_service/interaction_replay.rb:48:in `find_response'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/mock_service/interaction_replay.rb:30:in `respond'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pact-mock_service-0.2.2/lib/pact/consumer/mock_service/app.rb:67:in `call'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'",
  "/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'"

```

**Comment by bethesque** [comment]
Done.
